

service: ims
 
provider:
 name: aws
 runtime: python3.9
 region: ap-southeast-2
 memorySize: 128
 iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource: 'arn:aws:dynamodb:ap-southeast-2:*:*'
package:
  exclude:
    - node_modules/**
    - dev/**
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
 wsgi:
   app: main.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: 'ANY /{proxy+}'
