
name: Deploy serverless app

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4 
      with:
        python-version: '3.9' 
    - run: python --version
    - run: python3 --version

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Serverless
      run: npm install -g serverless
    - name: Install Dependency
      run: pip install -r requirements.txt
    - name: Install Serverless WSGI plugin
      run: sls plugin install -n serverless-wsgi
    - name: Install Serverless python reqirement plugin
      run: sls plugin install -n serverless-python-requirements

    - name: Serverless Authentication
      run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
    
    - name: Deploy to AWS
      run: serverless deploy --verbose
        
#     - name: serverless deploy
#       run: serverless deploy
#       uses: serverless/github-action@master
#       with:
#         args: deploy
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: serverless doctor
      run: serverless doctor
