
name: Deploy serverless app

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Serverless
      run: npm install -g serverless
    - name: Install Dependency
      run: pip install -r requirements.txt
    - name: Install Serverless WSGI plugin
      run: sls plugin install -n serverless-wsgi
    - name: Install Serverless python reqirement plugin
      run: sls plugin install -n serverless-python-requirements

    - name: serverless login
      run: serverless config credentials --provider aws --key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --secret ${{ secrets.AWS_ACCESS_KEY_ID }} -o

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}